# Generated by Django 3.0.6 on 2020-05-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('zone', models.TextField()),
                ('zoneID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.TextField()),
                ('price', models.FloatField()),
                ('itemType', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopType', models.TextField()),
                ('name', models.TextField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('zone', models.TextField()),
                ('zoneID', models.IntegerField()),
                ('slotID', models.IntegerField()),
                ('numCust', models.IntegerField(default=0)),
            ],
        ),
    ]
